FEAT: if tests' ok, push ok

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,9 +21,24 @@ jobs:
         run: |
           pip install -r app/v1/src/environment_configs/requirements.txt
       - name: Test
+        id: test_result
         run: |
           echo "Assigning the app root directory path value to PYTHONPATH"
           export PYTHONPATH=$PWD/app
           
           echo "Running tests"
           pytest app/v1/test
+        continue-on-error: true
+  prevent_push_on_tests_failure:
+    name: Prevent Push on Tests Failure
+    runs-on: ubuntu-latest
+    needs: build_and_test
+    steps:
+      - name: Check Test Result
+        run: |
+          if [[ "${{ needs.build_and_test.outputs.test_result }}" == "failure" ]]; then
+            echo "Tests failed. Blocking push."
+            exit 1
+          else
+            echo "Tests passed. Push allowed."
+          fi
